#ifndef MCU_DEFINITIONS_H
#define MCU_DEFINITIONS_H

enum ModemState
{
    MODEM_STATE_INIT_DEVICE,
    MODEM_STATE_DEVICE,
    MODEM_STATE_INIT_NODE,
    MODEM_STATE_NODE,
    MODEM_STATE_UNKNOWN,
};

#endif
