#ifndef MESH_GENERIC_BATTERY_H
#define MESH_GENERIC_BATTERY_H

#define BATTERY_LEVEL_MAX 0x64
#define BATTERY_LEVEL_UNKNOWN 0xFF

#define BATTERY_TIME_TO_DISCHARGE_UNKNOWN 0xFFFFFF

#define BATTERY_TIME_TO_CHARGE_UNKNOWN 0xFFFFFF

#define BATTERY_FLAGS_PRESENCE_NOT_PRESENT (0b00 << 0)
#define BATTERY_FLAGS_PRESENCE_PRESENT_AND_REMOVABLE (0b01 << 0)
#define BATTERY_FLAGS_PRESENCE_PRESENT_AND_NON_REMOVABLE (0b10 << 0)
#define BATTERY_FLAGS_PRESENCE_UNKNOWN (0b11 << 0)

#define BATTERY_FLAGS_INDICATOR_CRITICALLY_LOW_LEVEL (0b00 << 2)
#define BATTERY_FLAGS_INDICATOR_LOW_LEVEL (0b01 << 2)
#define BATTERY_FLAGS_INDICATOR_GOOD_LEVEL (0b10 << 2)
#define BATTERY_FLAGS_INDICATOR_UNKNOWN (0b11 << 2)

#define BATTERY_FLAGS_CHARGING_IS_NOT_CHARGEABLE (0b00 << 4)
#define BATTERY_FLAGS_CHARGING_IS_CHARGEABLE_AND_IS_NOT_CHARGING (0b01 << 4)
#define BATTERY_FLAGS_CHARGING_IS_CHARGEABLE_AND_IS_CHARGING (0b10 << 4)
#define BATTERY_FLAGS_CHARGING_UNKNOWN (0b11 << 4)

#define BATTERY_FLAGS_SERVICEABILITY_RFU (0b00 << 6)
#define BATTERY_FLAGS_SERVICEABILITY_BATTERY_DOES_NOT_REQUIRE_SERVICE (0b01 << 6)
#define BATTERY_FLAGS_SERVICEABILITY_BATTERY_REQUIRES_SERVICE (0b10 << 6)
#define BATTERY_FLAGS_SERVICEABILITY_UNKNOWN (0b11 << 6)

#endif
